@host = localhost
@port = 8080
@pathproject = academico-web-api


###Lista todos os endereços
GET http://{{host}}:{{port}}/{{pathproject}}/enderecos

###Busca um endereço especifico por id
GET http://{{host}}:{{port}}/{{pathproject}}/enderecos/345

###Criar um endereço 
POST http://{{host}}:{{port}}/{{pathproject}}/enderecos
Content-type: application/json

{
    "CEP": 46000,
    "rua": "rua sD",
    "bairro": "bairro D",
    "cidade": "cidade D",
    "estado": "estado D"
}

###Atualizar todos os atributos de um endereço
PUT http://{{host}}:{{port}}/{{pathproject}}/enderecos/100
Content-type: application/json

{   
    "CEP": 467979,
    "rua": "rua D",
    "bairro": "bairro D",
    "cidade": "cidade D",
    "estado": "estado D"
}

###Deletar um endereço
DELETE http://{{host}}:{{port}}/{{pathproject}}/enderecos/12

###Ativar ou desativar um endereço - Não CRUD
PUT  http://{{host}}:{{port}}/{{pathproject}}/enderecos/12/status
Content-Type: text/plain

DESATIVO
